# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_knx_log.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#  >>  pyuic5 -x GUI_knx_log.ui -o GUI_knx_log.py


from PyQt5 import QtCore, QtGui, QtWidgets
from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect, QSize, QTime, QUrl, Qt, QEvent)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1250, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(53, 53, 53);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMaximumSize(QtCore.QSize(600, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.Btn_Menu = QtWidgets.QPushButton(self.frame_4)
        self.Btn_Menu.setMinimumSize(QtCore.QSize(88, 50))
        self.Btn_Menu.setStyleSheet("QPushButton {\n"
                                    "    border: 0px solid;\n"
                                    "    background-color: rgb(109, 109, 109);\n"
                                    "    \n"
                                    "    color: rgb(255, 255, 255);\n"
                                    "}\n"
                                    "QPushButton:hover {\n"
                                    "    background-color: rgb(136, 136, 136);\n"
                                    "\n"
                                    "}\n"
                                    "QPushButton:pressed {    \n"
                                    "    background-color: rgb(85, 170, 255);\n"
                                    "}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/20x20/cil-menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Menu.setIcon(icon)
        self.Btn_Menu.setIconSize(QtCore.QSize(20, 20))
        self.Btn_Menu.setObjectName("Btn_Menu")
        self.horizontalLayout_14.addWidget(self.Btn_Menu)
        self.stackedWidget_MenuBar_1 = QtWidgets.QStackedWidget(self.frame_4)
        self.stackedWidget_MenuBar_1.setObjectName("stackedWidget_MenuBar_1")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.Btn_HomePage = QtWidgets.QPushButton(self.page)
        self.Btn_HomePage.setGeometry(QtCore.QRect(20, 10, 75, 23))
        self.Btn_HomePage.setStyleSheet("QPushButton {\n"
                                        "    border: 0px solid;\n"
                                        "    background-color: rgb(109, 109, 109);\n"
                                        "    border-radius: 3px;\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(136, 136, 136);\n"
                                        "\n"
                                        "}\n"
                                        "QPushButton:pressed {    \n"
                                        "    background-color: rgb(85, 170, 255);\n"
                                        "}")
        self.Btn_HomePage.setObjectName("Btn_HomePage")
        self.Btn_XMLPage = QtWidgets.QPushButton(self.page)
        self.Btn_XMLPage.setGeometry(QtCore.QRect(120, 10, 75, 23))
        self.Btn_XMLPage.setStyleSheet("QPushButton {\n"
                                       "    border: 0px solid;\n"
                                       "    background-color: rgb(109, 109, 109);\n"
                                       "    border-radius: 3px;\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "}\n"
                                       "QPushButton:hover {\n"
                                       "    background-color: rgb(136, 136, 136);\n"
                                       "\n"
                                       "}\n"
                                       "QPushButton:pressed {    \n"
                                       "    background-color: rgb(85, 170, 255);\n"
                                       "}")
        self.Btn_XMLPage.setObjectName("Btn_XMLPage")
        self.Btn_SettingPage = QtWidgets.QPushButton(self.page)
        self.Btn_SettingPage.setGeometry(QtCore.QRect(220, 10, 75, 23))
        self.Btn_SettingPage.setStyleSheet("QPushButton {\n"
                                           "    border: 0px solid;\n"
                                           "    background-color: rgb(109, 109, 109);\n"
                                           "    border-radius: 3px;\n"
                                           "    color: rgb(255, 255, 255);\n"
                                           "}\n"
                                           "QPushButton:hover {\n"
                                           "    background-color: rgb(136, 136, 136);\n"
                                           "\n"
                                           "}\n"
                                           "QPushButton:pressed {    \n"
                                           "    background-color: rgb(85, 170, 255);\n"
                                           "}")
        self.Btn_SettingPage.setObjectName("Btn_SettingPage")
        self.Btn_LogPage_inf = QtWidgets.QPushButton(self.page)
        self.Btn_LogPage_inf.setGeometry(QtCore.QRect(320, 10, 75, 23))
        self.Btn_LogPage_inf.setStyleSheet("QPushButton {\n"
                                           "    border: 0px solid;\n"
                                           "    background-color: rgb(109, 109, 109);\n"
                                           "    border-radius: 3px;\n"
                                           "    color: rgb(255, 255, 255);\n"
                                           "}\n"
                                           "QPushButton:hover {\n"
                                           "    background-color: rgb(136, 136, 136);\n"
                                           "\n"
                                           "}\n"
                                           "QPushButton:pressed {    \n"
                                           "    background-color: rgb(85, 170, 255);\n"
                                           "}")
        self.Btn_LogPage_inf.setObjectName("Btn_LogPage_inf")
        self.Btn_LogPage_inf_2 = QtWidgets.QPushButton(self.page)
        self.Btn_LogPage_inf_2.setGeometry(QtCore.QRect(420, 10, 75, 23))
        self.Btn_LogPage_inf_2.setStyleSheet("QPushButton {\n"
                                             "    border: 0px solid;\n"
                                             "    background-color: rgb(109, 109, 109);\n"
                                             "    border-radius: 3px;\n"
                                             "    color: rgb(255, 255, 255);\n"
                                             "}\n"
                                             "QPushButton:hover {\n"
                                             "    background-color: rgb(136, 136, 136);\n"
                                             "\n"
                                             "}\n"
                                             "QPushButton:pressed {    \n"
                                             "    background-color: rgb(85, 170, 255);\n"
                                             "}")
        self.Btn_LogPage_inf_2.setObjectName("Btn_LogPage_inf_2")
        self.stackedWidget_MenuBar_1.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget_MenuBar_1.addWidget(self.page_2)
        self.horizontalLayout_14.addWidget(self.stackedWidget_MenuBar_1)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Btn_Profile = QtWidgets.QPushButton(self.frame_6)
        self.Btn_Profile.setMinimumSize(QtCore.QSize(91, 51))
        self.Btn_Profile.setMaximumSize(QtCore.QSize(91, 51))
        self.Btn_Profile.setStyleSheet("QPushButton {\n"
                                       "    border: 0px solid;\n"
                                       "    background-color: rgb(109, 109, 109);\n"
                                       "    \n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "}\n"
                                       "QPushButton:hover {\n"
                                       "    background-color: rgb(136, 136, 136);\n"
                                       "}\n"
                                       "QPushButton:pressed {    \n"
                                       "    background-color: rgb(85, 170, 255);\n"
                                       "}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/24x24/cil-user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Profile.setIcon(icon1)
        self.Btn_Profile.setIconSize(QtCore.QSize(20, 20))
        self.Btn_Profile.setObjectName("Btn_Profile")
        self.horizontalLayout_4.addWidget(self.Btn_Profile)
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setMinimumSize(QtCore.QSize(120, 51))
        self.frame_7.setMaximumSize(QtCore.QSize(120, 51))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.Btn_CloseWindow = QtWidgets.QPushButton(self.frame_7)
        self.Btn_CloseWindow.setGeometry(QtCore.QRect(90, 10, 20, 20))
        self.Btn_CloseWindow.setMinimumSize(QtCore.QSize(20, 20))
        self.Btn_CloseWindow.setMaximumSize(QtCore.QSize(20, 20))
        self.Btn_CloseWindow.setStyleSheet("QPushButton {\n"
                                           "    border: 0px solid;\n"
                                           "    color: rgb(255, 255, 255);\n"
                                           "}\n"
                                           "QPushButton:hover {\n"
                                           "    \n"
                                           "    background-color: rgb(255, 0, 4);\n"
                                           "\n"
                                           "}")
        self.Btn_CloseWindow.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/20x20/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_CloseWindow.setIcon(icon2)
        self.Btn_CloseWindow.setIconSize(QtCore.QSize(18, 18))
        self.Btn_CloseWindow.setObjectName("Btn_CloseWindow")
        self.Btn_DownWindow = QtWidgets.QPushButton(self.frame_7)
        self.Btn_DownWindow.setGeometry(QtCore.QRect(30, 10, 20, 20))
        self.Btn_DownWindow.setMinimumSize(QtCore.QSize(20, 20))
        self.Btn_DownWindow.setMaximumSize(QtCore.QSize(20, 20))
        self.Btn_DownWindow.setStyleSheet("QPushButton {\n"
                                          "    border: 0px solid;\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "}\n"
                                          "QPushButton:hover {\n"
                                          "    \n"
                                          "    background-color: rgb(0, 170, 255);\n"
                                          "\n"
                                          "}")
        self.Btn_DownWindow.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/20x20/cil-window-minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_DownWindow.setIcon(icon3)
        self.Btn_DownWindow.setIconSize(QtCore.QSize(18, 18))
        self.Btn_DownWindow.setObjectName("Btn_DownWindow")
        self.Btn_DownWindow_2 = QtWidgets.QPushButton(self.frame_7)
        self.Btn_DownWindow_2.setGeometry(QtCore.QRect(60, 10, 20, 20))
        self.Btn_DownWindow_2.setMinimumSize(QtCore.QSize(20, 20))
        self.Btn_DownWindow_2.setMaximumSize(QtCore.QSize(20, 20))
        self.Btn_DownWindow_2.setStyleSheet("QPushButton {\n"
                                            "    border: 0px solid;\n"
                                            "    color: rgb(255, 255, 255);\n"
                                            "}\n"
                                            "QPushButton:hover {\n"
                                            "    \n"
                                            "    background-color: rgb(0, 170, 255);\n"
                                            "\n"
                                            "}")
        self.Btn_DownWindow_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/24x24/cil-window-restore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_DownWindow_2.setIcon(icon4)
        self.Btn_DownWindow_2.setIconSize(QtCore.QSize(18, 18))
        self.Btn_DownWindow_2.setObjectName("Btn_DownWindow_2")
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.horizontalLayout_3.addWidget(self.frame_6, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color: rgb(108, 108, 108);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Page_settings = QtWidgets.QWidget()
        self.Page_settings.setObjectName("Page_settings")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.Page_settings)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Menu_Settings = QtWidgets.QFrame(self.Page_settings)
        self.Menu_Settings.setMinimumSize(QtCore.QSize(296, 0))
        self.Menu_Settings.setMaximumSize(QtCore.QSize(296, 16777215))
        self.Menu_Settings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Menu_Settings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Menu_Settings.setObjectName("Menu_Settings")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Menu_Settings)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.LeftMenu = QtWidgets.QFrame(self.Menu_Settings)
        self.LeftMenu.setMinimumSize(QtCore.QSize(92, 1800))
        self.LeftMenu.setMaximumSize(QtCore.QSize(92, 16777215))
        self.LeftMenu.setStyleSheet("background-color: rgb(53, 53, 53);")
        self.LeftMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LeftMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LeftMenu.setObjectName("LeftMenu")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.LeftMenu)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.LeftMenu)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_5.setStyleSheet("background-color: rgb(80, 80, 80);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Btn_Home = QtWidgets.QPushButton(self.frame_5)
        self.Btn_Home.setMinimumSize(QtCore.QSize(0, 50))
        self.Btn_Home.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Btn_Home.setStyleSheet("QPushButton{\n"
                                    "    border: 1px solid;\n"
                                    "    border-color: rgb(120, 120, 120);\n"
                                    "\n"
                                    "    color: rgb(255, 255, 255);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(0, 170, 255);\n"
                                    "    border-color: rgb(120, 120, 120);\n"
                                    "}\n"
                                    "QPushButton:pressed {    \n"
                                    "    background-color: rgb(85, 170, 255);\n"
                                    "}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/20x20/cil-home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Home.setIcon(icon5)
        self.Btn_Home.setObjectName("Btn_Home")
        self.verticalLayout_2.addWidget(self.Btn_Home)
        self.tableWidgetforHome = QtWidgets.QTableWidget(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetforHome.sizePolicy().hasHeightForWidth())
        self.tableWidgetforHome.setSizePolicy(sizePolicy)
        self.tableWidgetforHome.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidgetforHome.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tableWidgetforHome.setStyleSheet("color: rgb(255, 255, 255);")
        self.tableWidgetforHome.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidgetforHome.setAutoScroll(True)
        self.tableWidgetforHome.setAutoScrollMargin(16)
        self.tableWidgetforHome.setRowCount(3)
        self.tableWidgetforHome.setColumnCount(1)
        self.tableWidgetforHome.setObjectName("tableWidgetforHome")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetforHome.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetforHome.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetforHome.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetforHome.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetforHome.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetforHome.setItem(2, 0, item)
        self.tableWidgetforHome.horizontalHeader().setVisible(False)
        self.tableWidgetforHome.horizontalHeader().setDefaultSectionSize(91)
        self.tableWidgetforHome.verticalHeader().setVisible(False)
        self.tableWidgetforHome.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidgetforHome.verticalHeader().setDefaultSectionSize(25)
        self.tableWidgetforHome.verticalHeader().setHighlightSections(True)
        self.tableWidgetforHome.verticalHeader().setMinimumSectionSize(25)
        self.tableWidgetforHome.verticalHeader().setSortIndicatorShown(False)
        self.tableWidgetforHome.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.tableWidgetforHome)
        self.Btn_Scenes = QtWidgets.QPushButton(self.frame_5)
        self.Btn_Scenes.setMinimumSize(QtCore.QSize(0, 50))
        self.Btn_Scenes.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Btn_Scenes.setStyleSheet("QPushButton{\n"
                                      "    border: 1px solid;\n"
                                      "    border-color: rgb(120, 120, 120);\n"
                                      "\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "    background-color: rgb(0, 170, 255);\n"
                                      "    border-color: rgb(120, 120, 120);\n"
                                      "}\n"
                                      "QPushButton:pressed {    \n"
                                      "    background-color: rgb(85, 170, 255);\n"
                                      "}")
        self.Btn_Scenes.setObjectName("Btn_Scenes")
        self.verticalLayout_2.addWidget(self.Btn_Scenes)
        self.Btn_All = QtWidgets.QPushButton(self.frame_5)
        self.Btn_All.setMinimumSize(QtCore.QSize(0, 50))
        self.Btn_All.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Btn_All.setStyleSheet("QPushButton{\n"
                                   "    border: 1px solid;\n"
                                   "    border-color: rgb(120, 120, 120);\n"
                                   "\n"
                                   "    color: rgb(255, 255, 255);\n"
                                   "}\n"
                                   "QPushButton:hover{\n"
                                   "    background-color: rgb(0, 170, 255);\n"
                                   "    border-color: rgb(120, 120, 120);\n"
                                   "}\n"
                                   "QPushButton:pressed {    \n"
                                   "    background-color: rgb(85, 170, 255);\n"
                                   "}")
        self.Btn_All.setObjectName("Btn_All")
        self.verticalLayout_2.addWidget(self.Btn_All)
        self.tableWidgetforHome.raise_()
        self.Btn_Home.raise_()
        self.Btn_Scenes.raise_()
        self.Btn_All.raise_()
        self.horizontalLayout_2.addWidget(self.frame_5, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_5.addWidget(self.LeftMenu, 0, QtCore.Qt.AlignTop)
        self.tableMenu1 = QtWidgets.QTableWidget(self.Menu_Settings)
        self.tableMenu1.setMinimumSize(QtCore.QSize(102, 0))
        self.tableMenu1.setMaximumSize(QtCore.QSize(102, 16777215))
        self.tableMenu1.setStyleSheet("QHeaderView::section:horizontal\n"
                                      "{\n"
                                      "    border: 1px solid rgb(32, 34, 42);\n"
                                      "    background-color:rgb(53, 53, 53);\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "}\n"
                                      "\n"
                                      " QScrollBar:vertical {\n"
                                      "    border: none;\n"
                                      "    background: rgb(52, 59, 72);\n"
                                      "    width: 14px;\n"
                                      "    border-radius: 0px;\n"
                                      " }")
        self.tableMenu1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableMenu1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableMenu1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableMenu1.setAutoScroll(True)
        self.tableMenu1.setShowGrid(True)
        self.tableMenu1.setRowCount(3)
        self.tableMenu1.setObjectName("tableMenu1")
        self.tableMenu1.setColumnCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableMenu1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMenu1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMenu1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMenu1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMenu1.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMenu1.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMenu1.setItem(2, 0, item)
        self.tableMenu1.horizontalHeader().setDefaultSectionSize(100)
        self.tableMenu1.verticalHeader().setVisible(False)
        self.horizontalLayout_5.addWidget(self.tableMenu1)
        self.tableMenu2 = QtWidgets.QTableWidget(self.Menu_Settings)
        self.tableMenu2.setMinimumSize(QtCore.QSize(102, 0))
        self.tableMenu2.setMaximumSize(QtCore.QSize(102, 16777215))
        self.tableMenu2.setStyleSheet("QHeaderView::section:horizontal\n"
                                      "{\n"
                                      "    border: 1px solid rgb(32, 34, 42);\n"
                                      "    background-color:rgb(53, 53, 53);\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "}\n"
                                      "\n"
                                      " QScrollBar:vertical {\n"
                                      "    border: none;\n"
                                      "    background: rgb(52, 59, 72);\n"
                                      "    width: 14px;\n"
                                      "    margin: 21px 0 21px 0;\n"
                                      "    border-radius: 0px;\n"
                                      " }")
        self.tableMenu2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableMenu2.setRowCount(5)
        self.tableMenu2.setObjectName("tableMenu2")
        self.tableMenu2.setColumnCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableMenu2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMenu2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMenu2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMenu2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMenu2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMenu2.setItem(4, 0, item)
        self.tableMenu2.horizontalHeader().setDefaultSectionSize(100)
        self.tableMenu2.verticalHeader().setVisible(False)
        self.horizontalLayout_5.addWidget(self.tableMenu2)
        self.horizontalLayout_7.addWidget(self.Menu_Settings)
        self.frame_3 = QtWidgets.QFrame(self.Page_settings)
        self.frame_3.setMinimumSize(QtCore.QSize(952, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_13 = QtWidgets.QFrame(self.frame_3)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.tableButtonsSet = QtWidgets.QTableWidget(self.frame_13)
        self.tableButtonsSet.setMinimumSize(QtCore.QSize(102, 0))
        self.tableButtonsSet.setMaximumSize(QtCore.QSize(102, 16777215))
        self.tableButtonsSet.setStyleSheet("QHeaderView::section:horizontal\n"
                                           "{\n"
                                           "    border: 1px solid rgb(32, 34, 42);\n"
                                           "    background-color:rgb(53, 53, 53);\n"
                                           "    color: rgb(255, 255, 255);\n"
                                           "}\n"
                                           "\n"
                                           " QScrollBar:vertical {\n"
                                           "    border: none;\n"
                                           "    background: rgb(52, 59, 72);\n"
                                           "    width: 14px;\n"
                                           "    margin: 21px 0 21px 0;\n"
                                           "    border-radius: 0px;\n"
                                           " }")
        self.tableButtonsSet.setObjectName("tableButtonsSet")
        self.tableButtonsSet.setColumnCount(1)
        self.tableButtonsSet.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableButtonsSet.setHorizontalHeaderItem(0, item)
        self.horizontalLayout_10.addWidget(self.tableButtonsSet)
        self.stackedWidget_Setting = QtWidgets.QStackedWidget(self.frame_13)
        self.stackedWidget_Setting.setMinimumSize(QtCore.QSize(500, 0))
        self.stackedWidget_Setting.setObjectName("stackedWidget_Setting")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setMinimumSize(QtCore.QSize(848, 0))
        self.page_3.setObjectName("page_3")
        self.gridLayout = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_23 = QtWidgets.QFrame(self.page_3)
        self.frame_23.setMinimumSize(QtCore.QSize(252, 161))
        self.frame_23.setMaximumSize(QtCore.QSize(252, 161))
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_23)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 41))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 41))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
                                      "    background-color: rgb(150,150,150);\n"
                                      "    border-radius: 5px;\n"
                                      "    border: 1px solid rgb(27, 29, 35);\n"
                                      "    padding-left: 10px;\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "}\n"
                                      "QLineEdit:hover {\n"
                                      "    border: 2px solid rgb(64, 71, 88);\n"
                                      "}\n"
                                      "QLineEdit:focus {\n"
                                      "    border: 2px solid rgb(91, 101, 124);\n"
                                      "}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_10.addWidget(self.lineEdit_2)
        self.frame_17 = QtWidgets.QFrame(self.frame_23)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_10.addWidget(self.frame_17)
        self.gridLayout.addWidget(self.frame_23, 1, 7, 1, 1)
        self.frame_16 = QtWidgets.QFrame(self.page_3)
        self.frame_16.setMinimumSize(QtCore.QSize(250, 161))
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 161))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.frame_35 = QtWidgets.QFrame(self.frame_16)
        self.frame_35.setStyleSheet("background-color: rgb(104, 104, 104);")
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_20.addWidget(self.frame_35)
        self.frame_34 = QtWidgets.QFrame(self.frame_16)
        self.frame_34.setMinimumSize(QtCore.QSize(230, 0))
        self.frame_34.setStyleSheet("background-color: rgb(102, 102, 102);")
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.formLayout = QtWidgets.QFormLayout(self.frame_34)
        self.formLayout.setContentsMargins(13, 0, 1, 1)
        self.formLayout.setSpacing(1)
        self.formLayout.setObjectName("formLayout")
        self.frame_19 = QtWidgets.QFrame(self.frame_34)
        self.frame_19.setMinimumSize(QtCore.QSize(100, 75))
        self.frame_19.setMaximumSize(QtCore.QSize(100, 75))
        self.frame_19.setStyleSheet("background-color: rgb(100,100,100);\n"
                                    "border: 1px solide;")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.label_5 = QtWidgets.QLabel(self.frame_19)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.label_5.setObjectName("label_5")
        self.btnToggleDayNight = QtWidgets.QPushButton(self.frame_19)
        self.btnToggleDayNight.setGeometry(QtCore.QRect(30, 40, 51, 31))
        self.btnToggleDayNight.setStyleSheet("border: 0px solid;\n"
                                             "")
        self.btnToggleDayNight.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/color/toggle_off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap("icons/color/toggle_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnToggleDayNight.setIcon(icon6)
        self.btnToggleDayNight.setIconSize(QtCore.QSize(40, 24))
        self.btnToggleDayNight.setCheckable(True)
        self.btnToggleDayNight.setObjectName("btnToggleDayNight")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.frame_19)
        self.frame_21 = QtWidgets.QFrame(self.frame_34)
        self.frame_21.setMinimumSize(QtCore.QSize(100, 75))
        self.frame_21.setMaximumSize(QtCore.QSize(100, 75))
        self.frame_21.setStyleSheet("background-color: rgb(100,100,100);\n"
                                    "border: 1px solide;")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.label_4 = QtWidgets.QLabel(self.frame_21)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.label_4.setObjectName("label_4")
        self.btnToggleLongShort = QtWidgets.QPushButton(self.frame_21)
        self.btnToggleLongShort.setGeometry(QtCore.QRect(20, 40, 61, 31))
        self.btnToggleLongShort.setStyleSheet("border: 0px solid;\n"
                                              "")
        self.btnToggleLongShort.setText("")
        self.btnToggleLongShort.setIcon(icon6)
        self.btnToggleLongShort.setIconSize(QtCore.QSize(40, 24))
        self.btnToggleLongShort.setCheckable(True)
        self.btnToggleLongShort.setObjectName("btnToggleLongShort")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frame_21)
        self.frame_29 = QtWidgets.QFrame(self.frame_34)
        self.frame_29.setMinimumSize(QtCore.QSize(100, 75))
        self.frame_29.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame_29.setStyleSheet("background-color: rgb(100,100,100);\n"
                                    "border: 1px solide;")
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.frame_29)
        self.frame_22 = QtWidgets.QFrame(self.frame_34)
        self.frame_22.setMinimumSize(QtCore.QSize(100, 75))
        self.frame_22.setMaximumSize(QtCore.QSize(100, 75))
        self.frame_22.setStyleSheet("background-color: rgb(100,100,100);\n"
                                    "border: 1px solide;")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.btnToggleChange = QtWidgets.QPushButton(self.frame_22)
        self.btnToggleChange.setGeometry(QtCore.QRect(20, 40, 61, 31))
        self.btnToggleChange.setStyleSheet("border: 0px solid;\n"
                                           "")
        self.btnToggleChange.setText("")
        self.btnToggleChange.setIcon(icon6)
        self.btnToggleChange.setIconSize(QtCore.QSize(40, 24))
        self.btnToggleChange.setCheckable(True)
        self.btnToggleChange.setObjectName("btnToggleChange")
        self.label_3 = QtWidgets.QLabel(self.frame_22)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.frame_22)
        self.horizontalLayout_20.addWidget(self.frame_34)
        self.frame_36 = QtWidgets.QFrame(self.frame_16)
        self.frame_36.setStyleSheet("background-color: rgb(104, 104, 104);")
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.horizontalLayout_20.addWidget(self.frame_36)
        self.gridLayout.addWidget(self.frame_16, 1, 5, 1, 1, QtCore.Qt.AlignVCenter)
        self.frame_28 = QtWidgets.QFrame(self.page_3)
        self.frame_28.setMinimumSize(QtCore.QSize(252, 252))
        self.frame_28.setMaximumSize(QtCore.QSize(252, 16777215))
        self.frame_28.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_28)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_15 = QtWidgets.QFrame(self.frame_28)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 71))
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 71))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.boxButtonsChoose = QtWidgets.QGroupBox(self.frame_15)
        self.boxButtonsChoose.setMinimumSize(QtCore.QSize(211, 51))
        self.boxButtonsChoose.setMaximumSize(QtCore.QSize(16777215, 51))
        self.boxButtonsChoose.setObjectName("boxButtonsChoose")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.boxButtonsChoose)
        self.verticalLayout_13.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_13.setSpacing(2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.comboBox = QtWidgets.QComboBox(self.boxButtonsChoose)
        self.comboBox.setMinimumSize(QtCore.QSize(80, 0))
        self.comboBox.setStyleSheet("QComboBox{\n"
                                    "    border: 1px solid;\n"
                                    "    border-color: rgb(120, 120, 120);\n"
                                    "    background-color: rgb(140, 140, 140);\n"
                                    "}\n"
                                    "QComboBox:hover{\n"
                                    "    border: 1px solid rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QComboBox QAbstractItemView {    \n"
                                    "    background-color: rgb(140, 140, 140);\n"
                                    "    border-color: rgb(120, 120, 120);\n"
                                    "    border: 1px solid rgb(0, 0, 0);\n"
                                    "    padding: 10px;\n"
                                    "    selection-background-color:  rgb(140, 140, 140);\n"
                                    "}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_13.addWidget(self.comboBox)
        self.verticalLayout_14.addWidget(self.boxButtonsChoose)
        self.verticalLayout_8.addWidget(self.frame_15, 0, QtCore.Qt.AlignRight | QtCore.Qt.AlignTop)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_28)
        self.groupBox_5.setStyleSheet("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit.setStyleSheet("border: 0px solid;\n"
                                    "border-color: rgb(120, 120, 120);")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_15.addWidget(self.textEdit)
        self.verticalLayout_8.addWidget(self.groupBox_5)
        self.frame_32 = QtWidgets.QFrame(self.frame_28)
        self.frame_32.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_32.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame_32.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_32.setStyleSheet("background-color: rgb(53, 53, 53);\n"
                                    "")
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_32)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 0, 191, 60))
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 20, 81, 31))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
                                        "    border: 1px solid;\n"
                                        "    border-color: rgb(120, 120, 120);\n"
                                        "    border-radius: 3px;\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: rgb(0, 170, 255);\n"
                                        "    border-color: rgb(120, 120, 120);\n"
                                        "}\n"
                                        "QPushButton:pressed {    \n"
                                        "    background-color: rgb(85, 170, 255);\n"
                                        "}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/16x16/cil-magnifying-glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_3.setIcon(icon7)
        self.pushButton_3.setIconSize(QtCore.QSize(13, 13))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_4.setGeometry(QtCore.QRect(100, 20, 81, 31))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
                                        "    border: 1px solid;\n"
                                        "    border-color: rgb(120, 120, 120);\n"
                                        "    border-radius: 3px;\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: rgb(0, 170, 255);\n"
                                        "    border-color: rgb(120, 120, 120);\n"
                                        "}\n"
                                        "QPushButton:pressed {    \n"
                                        "    background-color: rgb(85, 170, 255);\n"
                                        "}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/16x16/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon8)
        self.pushButton_4.setIconSize(QtCore.QSize(13, 13))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_8.addWidget(self.frame_32)
        self.frame_31 = QtWidgets.QFrame(self.frame_28)
        self.frame_31.setMinimumSize(QtCore.QSize(0, 71))
        self.frame_31.setMaximumSize(QtCore.QSize(16777215, 71))
        self.frame_31.setStyleSheet("background-color: rgb(53, 53, 53);\n"
                                    "border-radius: 3px;")
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_30 = QtWidgets.QFrame(self.frame_31)
        self.frame_30.setMaximumSize(QtCore.QSize(212, 16777215))
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.Btn_Resume_Set = QtWidgets.QPushButton(self.frame_30)
        self.Btn_Resume_Set.setMinimumSize(QtCore.QSize(90, 50))
        self.Btn_Resume_Set.setMaximumSize(QtCore.QSize(90, 50))
        self.Btn_Resume_Set.setStyleSheet("QPushButton{\n"
                                          "    border: 1px solid;\n"
                                          "    border-color: rgb(120, 120, 120);\n"
                                          "    \n"
                                          "    background-color: rgb(80, 80, 80);\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "}\n"
                                          "QPushButton:hover{\n"
                                          "    background-color: rgb(0, 170, 255);\n"
                                          "    border-color: rgb(120, 120, 120);\n"
                                          "}\n"
                                          "QPushButton:pressed {    \n"
                                          "    background-color: rgb(85, 170, 255);\n"
                                          "}")
        self.Btn_Resume_Set.setObjectName("Btn_Resume_Set")
        self.horizontalLayout_18.addWidget(self.Btn_Resume_Set)
        self.Btn_SaveAll_Set = QtWidgets.QPushButton(self.frame_30)
        self.Btn_SaveAll_Set.setMinimumSize(QtCore.QSize(90, 50))
        self.Btn_SaveAll_Set.setMaximumSize(QtCore.QSize(90, 50))
        self.Btn_SaveAll_Set.setStyleSheet("QPushButton{\n"
                                           "    border: 1px solid;\n"
                                           "    border-color: rgb(120, 120, 120);\n"
                                           "    background-color: rgb(80, 80, 80);\n"
                                           "    color: rgb(255, 255, 255);\n"
                                           "}\n"
                                           "QPushButton:hover{\n"
                                           "    background-color: rgb(0, 170, 255);\n"
                                           "    border-color: rgb(120, 120, 120);\n"
                                           "}\n"
                                           "QPushButton:pressed {    \n"
                                           "    background-color: rgb(85, 170, 255);\n"
                                           "}")
        self.Btn_SaveAll_Set.setObjectName("Btn_SaveAll_Set")
        self.horizontalLayout_18.addWidget(self.Btn_SaveAll_Set)
        self.verticalLayout_9.addWidget(self.frame_30)
        self.verticalLayout_8.addWidget(self.frame_31)
        self.gridLayout.addWidget(self.frame_28, 4, 7, 1, 1, QtCore.Qt.AlignRight)
        self.frame_27 = QtWidgets.QFrame(self.page_3)
        self.frame_27.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_27.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.stackedWforButtons = QtWidgets.QStackedWidget(self.frame_27)
        self.stackedWforButtons.setObjectName("stackedWforButtons")
        self.page_But1 = QtWidgets.QWidget()
        self.page_But1.setObjectName("page_But1")
        self.stackedWforButtons.addWidget(self.page_But1)
        self.page_But1xLong = QtWidgets.QWidget()
        self.page_But1xLong.setObjectName("page_But1xLong")
        self.stackedWforButtons.addWidget(self.page_But1xLong)
        self.page_But2 = QtWidgets.QWidget()
        self.page_But2.setObjectName("page_But2")
        self.stackedWforButtons.addWidget(self.page_But2)
        self.page_But2xLong = QtWidgets.QWidget()
        self.page_But2xLong.setObjectName("page_But2xLong")
        self.stackedWforButtons.addWidget(self.page_But2xLong)
        self.page_But4 = QtWidgets.QWidget()
        self.page_But4.setObjectName("page_But4")
        self.frame_But_4 = QtWidgets.QFrame(self.page_But4)
        self.frame_But_4.setGeometry(QtCore.QRect(20, 120, 208, 208))
        self.frame_But_4.setMinimumSize(QtCore.QSize(208, 208))
        self.frame_But_4.setMaximumSize(QtCore.QSize(208, 208))
        self.frame_But_4.setStyleSheet("border: 2px solid;\n"
                                       "border-color: rgb(120, 120, 120);")
        self.frame_But_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_But_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_But_4.setObjectName("frame_But_4")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_But_4)
        self.formLayout_2.setContentsMargins(1, 1, 1, 1)
        self.formLayout_2.setSpacing(1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.n1_bnt_But4 = QtWidgets.QPushButton(self.frame_But_4)
        self.n1_bnt_But4.setMinimumSize(QtCore.QSize(100, 100))
        self.n1_bnt_But4.setStyleSheet("QPushButton {\n"
                                       "    border: 1px solid;\n"
                                       "    border-color: rgb(120, 120, 120);\n"
                                       "    background-color: rgb(109, 109, 109);\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "}\n"
                                       "QPushButton:hover {\n"
                                       "    background-color: rgb(136, 136, 136);\n"
                                       "\n"
                                       "}\n"
                                       "QPushButton:pressed {    \n"
                                       "    background-color: rgb(85, 170, 255);\n"
                                       "}")
        self.n1_bnt_But4.setCheckable(True)
        self.n1_bnt_But4.setObjectName("n1_bnt_But4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.n1_bnt_But4)
        self.n2_bnt_But4 = QtWidgets.QPushButton(self.frame_But_4)
        self.n2_bnt_But4.setMinimumSize(QtCore.QSize(100, 100))
        self.n2_bnt_But4.setStyleSheet("QPushButton {\n"
                                       "    border: 1px solid;\n"
                                       "    border-color: rgb(120, 120, 120);\n"
                                       "    background-color: rgb(109, 109, 109);\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "}\n"
                                       "QPushButton:hover {\n"
                                       "    background-color: rgb(136, 136, 136);\n"
                                       "\n"
                                       "}\n"
                                       "QPushButton:pressed {    \n"
                                       "    background-color: rgb(85, 170, 255);\n"
                                       "}")
        self.n2_bnt_But4.setCheckable(True)
        self.n2_bnt_But4.setObjectName("n2_bnt_But4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.n2_bnt_But4)
        self.n4_bnt_But4 = QtWidgets.QPushButton(self.frame_But_4)
        self.n4_bnt_But4.setMinimumSize(QtCore.QSize(100, 100))
        self.n4_bnt_But4.setStyleSheet("QPushButton {\n"
                                       "    border: 1px solid;\n"
                                       "    border-color: rgb(120, 120, 120);\n"
                                       "    background-color: rgb(109, 109, 109);\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "}\n"
                                       "QPushButton:hover {\n"
                                       "    background-color: rgb(136, 136, 136);\n"
                                       "\n"
                                       "}\n"
                                       "QPushButton:pressed {    \n"
                                       "    background-color: rgb(85, 170, 255);\n"
                                       "}")
        self.n4_bnt_But4.setCheckable(True)
        self.n4_bnt_But4.setObjectName("n4_bnt_But4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.n4_bnt_But4)
        self.n3_bnt_But4 = QtWidgets.QPushButton(self.frame_But_4)
        self.n3_bnt_But4.setMinimumSize(QtCore.QSize(100, 100))
        self.n3_bnt_But4.setStyleSheet("QPushButton {\n"
                                       "    border: 1px solid;\n"
                                       "    border-color: rgb(120, 120, 120);\n"
                                       "    background-color: rgb(109, 109, 109);\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "}\n"
                                       "QPushButton:hover {\n"
                                       "    background-color: rgb(136, 136, 136);\n"
                                       "\n"
                                       "}\n"
                                       "QPushButton:pressed {    \n"
                                       "    background-color: rgb(85, 170, 255);\n"
                                       "}")
        self.n3_bnt_But4.setCheckable(True)
        self.n3_bnt_But4.setObjectName("n3_bnt_But4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.n3_bnt_But4)
        self.stackedWforButtons.addWidget(self.page_But4)
        self.page_But4xLong = QtWidgets.QWidget()
        self.page_But4xLong.setObjectName("page_But4xLong")
        self.stackedWforButtons.addWidget(self.page_But4xLong)
        self.verticalLayout_11.addWidget(self.stackedWforButtons)
        self.gridLayout.addWidget(self.frame_27, 4, 5, 1, 1)
        self.frame_12 = QtWidgets.QFrame(self.page_3)
        self.frame_12.setMinimumSize(QtCore.QSize(346, 161))
        self.frame_12.setMaximumSize(QtCore.QSize(540, 161))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox = QtWidgets.QGroupBox(self.frame_12)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_14 = QtWidgets.QFrame(self.groupBox)
        self.frame_14.setMinimumSize(QtCore.QSize(291, 61))
        self.frame_14.setMaximumSize(QtCore.QSize(500, 61))
        self.frame_14.setStyleSheet("background-color: rgb(100,100,100);\n"
                                    "border: 1px solide;")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_14)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 41))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 41))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
                                    "    background-color: rgb(150,150,150);\n"
                                    "    border-radius: 5px;\n"
                                    "    border: 1px solid rgb(27, 29, 35);\n"
                                    "    padding-left: 10px;\n"
                                    "    color: rgb(255, 255, 255);\n"
                                    "}\n"
                                    "QLineEdit:hover {\n"
                                    "    border: 2px solid rgb(64, 71, 88);\n"
                                    "}\n"
                                    "QLineEdit:focus {\n"
                                    "    border: 2px solid rgb(91, 101, 124);\n"
                                    "}")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_19.addWidget(self.lineEdit)
        self.Bts_Save_Name = QtWidgets.QPushButton(self.frame_14)
        self.Bts_Save_Name.setMinimumSize(QtCore.QSize(51, 41))
        self.Bts_Save_Name.setMaximumSize(QtCore.QSize(51, 41))
        self.Bts_Save_Name.setStyleSheet("QPushButton {\n"
                                         "    border: 0px solid;\n"
                                         "    background-color: rgb(109, 109, 109);\n"
                                         "    border-radius: 3px;\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "}\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: rgb(136, 136, 136);\n"
                                         "\n"
                                         "}\n"
                                         "QPushButton:pressed {    \n"
                                         "    background-color: rgb(85, 170, 255);\n"
                                         "}")
        self.Bts_Save_Name.setObjectName("Bts_Save_Name")
        self.horizontalLayout_19.addWidget(self.Bts_Save_Name)
        self.verticalLayout_7.addWidget(self.frame_14)
        self.horizontalLayout_8.addWidget(self.groupBox)
        self.gridLayout.addWidget(self.frame_12, 1, 2, 1, 1)
        self.frame_26 = QtWidgets.QFrame(self.page_3)
        self.frame_26.setMinimumSize(QtCore.QSize(346, 0))
        self.frame_26.setMaximumSize(QtCore.QSize(540, 16777215))
        self.frame_26.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_26)
        self.groupBox_3.setMinimumSize(QtCore.QSize(161, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_17.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_17.setSpacing(1)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.horizontalLayout_17.addWidget(self.tableWidget_3)
        self.horizontalLayout_11.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_26)
        self.groupBox_2.setMinimumSize(QtCore.QSize(161, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.verticalLayout_6.addWidget(self.tableWidget_2)
        self.horizontalLayout_11.addWidget(self.groupBox_2)
        self.gridLayout.addWidget(self.frame_26, 4, 2, 1, 1)
        self.stackedWidget_Setting.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget_Setting.addWidget(self.page_4)
        self.horizontalLayout_10.addWidget(self.stackedWidget_Setting)
        self.horizontalLayout_9.addWidget(self.frame_13)
        self.horizontalLayout_7.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.Page_settings)
        self.Page_XML = QtWidgets.QWidget()
        self.Page_XML.setObjectName("Page_XML")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.Page_XML)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_25 = QtWidgets.QFrame(self.Page_XML)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.table_forLog = QtWidgets.QTableWidget(self.frame_25)
        self.table_forLog.setStyleSheet("QHeaderView::section:horizontal\n"
                                        "{\n"
                                        "    border: 1px solid rgb(32, 34, 42);\n"
                                        "    background-color:rgb(53, 53, 53);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "}\n"
                                        "\n"
                                        " QScrollBar:vertical {\n"
                                        "    border: none;\n"
                                        "    background: rgb(52, 59, 72);\n"
                                        "    width: 14px;\n"
                                        "    border-radius: 0px;\n"
                                        " }")
        self.table_forLog.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.table_forLog.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table_forLog.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_forLog.setAutoScroll(False)
        self.table_forLog.setEditTriggers(
            QtWidgets.QAbstractItemView.AnyKeyPressed | QtWidgets.QAbstractItemView.DoubleClicked | QtWidgets.QAbstractItemView.EditKeyPressed | QtWidgets.QAbstractItemView.SelectedClicked)
        self.table_forLog.setAlternatingRowColors(False)
        self.table_forLog.setShowGrid(True)
        self.table_forLog.setWordWrap(True)
        self.table_forLog.setRowCount(0)
        self.table_forLog.setObjectName("table_forLog")
        self.table_forLog.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_forLog.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_forLog.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_forLog.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_forLog.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_forLog.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_forLog.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_forLog.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_forLog.setHorizontalHeaderItem(7, item)
        self.table_forLog.horizontalHeader().setVisible(False)
        self.table_forLog.horizontalHeader().setCascadingSectionResizes(False)
        self.table_forLog.horizontalHeader().setDefaultSectionSize(130)
        self.table_forLog.horizontalHeader().setHighlightSections(True)
        self.table_forLog.horizontalHeader().setSortIndicatorShown(False)
        self.table_forLog.horizontalHeader().setStretchLastSection(True)
        self.table_forLog.verticalHeader().setVisible(False)
        self.table_forLog.verticalHeader().setCascadingSectionResizes(False)
        self.table_forLog.verticalHeader().setHighlightSections(False)
        self.table_forLog.verticalHeader().setSortIndicatorShown(False)
        self.table_forLog.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.table_forLog)
        self.frame_18 = QtWidgets.QFrame(self.frame_25)
        self.frame_18.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_18.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_24 = QtWidgets.QFrame(self.frame_18)
        self.frame_24.setMaximumSize(QtCore.QSize(150, 50))
        self.frame_24.setStyleSheet("background-color: rgb(100,100,100);\n"
                                    "border-radius: 3px;")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.Open_XML = QtWidgets.QPushButton(self.frame_24)
        self.Open_XML.setMinimumSize(QtCore.QSize(0, 30))
        self.Open_XML.setStyleSheet("QPushButton {\n"
                                    "    border: 1px solid;\n"
                                    "    background-color: rgb(109, 109, 109);\n"
                                    "    \n"
                                    "    color: rgb(255, 255, 255);\n"
                                    "}\n"
                                    "QPushButton:hover {\n"
                                    "    background-color: rgb(136, 136, 136);\n"
                                    "\n"
                                    "}\n"
                                    "QPushButton:pressed {    \n"
                                    "    background-color: rgb(85, 170, 255);\n"
                                    "}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../PycharmProjects/Simple_PySide_Base-master/icons/16x16/cil-folder-open.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Open_XML.setIcon(icon9)
        self.Open_XML.setObjectName("Open_XML")
        self.horizontalLayout_16.addWidget(self.Open_XML)
        self.Read_XML = QtWidgets.QPushButton(self.frame_24)
        self.Read_XML.setMinimumSize(QtCore.QSize(0, 30))
        self.Read_XML.setStyleSheet("QPushButton {\n"
                                    "    border: 1px solid;\n"
                                    "    background-color: rgb(109, 109, 109);\n"
                                    "    \n"
                                    "    color: rgb(255, 255, 255);\n"
                                    "}\n"
                                    "QPushButton:hover {\n"
                                    "    background-color: rgb(136, 136, 136);\n"
                                    "\n"
                                    "}\n"
                                    "QPushButton:pressed {    \n"
                                    "    background-color: rgb(85, 170, 255);\n"
                                    "}")
        self.Read_XML.setObjectName("Read_XML")
        self.horizontalLayout_16.addWidget(self.Read_XML)
        self.horizontalLayout_13.addWidget(self.frame_24)
        self.frame_8 = QtWidgets.QFrame(self.frame_18)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.Open_File_XML_ETSgroup = QtWidgets.QLineEdit(self.frame_8)
        self.Open_File_XML_ETSgroup.setGeometry(QtCore.QRect(10, 10, 511, 41))
        self.Open_File_XML_ETSgroup.setStyleSheet("\n"
                                                  "QLineEdit {\n"
                                                  "    background-color: rgb(27, 29, 35);\n"
                                                  "    border-radius: 5px;\n"
                                                  "    border: 2px solid rgb(27, 29, 35);\n"
                                                  "    padding-left: 10px;\n"
                                                  "    color: rgb(255, 255, 255);\n"
                                                  "}\n"
                                                  "QLineEdit:hover {\n"
                                                  "    border: 2px solid rgb(64, 71, 88);\n"
                                                  "}\n"
                                                  "QLineEdit:focus {\n"
                                                  "    border: 2px solid rgb(91, 101, 124);\n"
                                                  "}")
        self.Open_File_XML_ETSgroup.setObjectName("Open_File_XML_ETSgroup")
        self.horizontalLayout_13.addWidget(self.frame_8)
        self.frame_20 = QtWidgets.QFrame(self.frame_18)
        self.frame_20.setMinimumSize(QtCore.QSize(300, 50))
        self.frame_20.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_20.setStyleSheet("background-color: rgb(100,100,100);\n"
                                    "border-radius: 3px;")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
                                        "    border: 1px solid;\n"
                                        "    background-color: rgb(109, 109, 109);\n"
                                        "    \n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(136, 136, 136);\n"
                                        "\n"
                                        "}\n"
                                        "QPushButton:pressed {    \n"
                                        "    background-color: rgb(85, 170, 255);\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_15.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.frame_20)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "    border: 1px solid;\n"
                                      "    background-color: rgb(109, 109, 109);\n"
                                      "    \n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: rgb(136, 136, 136);\n"
                                      "\n"
                                      "}\n"
                                      "QPushButton:pressed {    \n"
                                      "    background-color: rgb(85, 170, 255);\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_15.addWidget(self.pushButton)
        self.horizontalLayout_13.addWidget(self.frame_20, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_4.addWidget(self.frame_18)
        self.horizontalLayout_12.addWidget(self.frame_25)
        self.stackedWidget.addWidget(self.Page_XML)
        self.Page_Index_Home = QtWidgets.QWidget()
        self.Page_Index_Home.setObjectName("Page_Index_Home")
        self.label = QtWidgets.QLabel(self.Page_Index_Home)
        self.label.setGeometry(QtCore.QRect(460, 300, 331, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Page_Index_Home)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 381, 31))
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.Page_Index_Home)
        self.Page_Log = QtWidgets.QWidget()
        self.Page_Log.setObjectName("Page_Log")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Page_Log)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_9 = QtWidgets.QFrame(self.Page_Log)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_10.setStyleSheet("")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_3.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_11)
        self.tableWidget.setStyleSheet("QHeaderView::section:horizontal\n"
                                       "{\n"
                                       "    border: 1px solid rgb(32, 34, 42);\n"
                                       "    background-color:rgb(53, 53, 53);\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "}\n"
                                       "\n"
                                       " QScrollBar:vertical {\n"
                                       "    border: none;\n"
                                       "    background: rgb(52, 59, 72);\n"
                                       "    width: 14px;\n"
                                       "    border-radius: 0px;\n"
                                       " }")
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(130)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.verticalLayout_3.addWidget(self.frame_11)
        self.horizontalLayout_6.addWidget(self.frame_9)
        self.stackedWidget.addWidget(self.Page_Log)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWforButtons.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_Menu.setText(_translate("MainWindow", "Menu"))
        self.Btn_HomePage.setText(_translate("MainWindow", "Home Page"))
        self.Btn_XMLPage.setText(_translate("MainWindow", "XML Page"))
        self.Btn_SettingPage.setText(_translate("MainWindow", "Setting Page"))
        self.Btn_LogPage_inf.setText(_translate("MainWindow", "Log Page"))
        self.Btn_LogPage_inf_2.setText(_translate("MainWindow", "Find Button"))
        self.Btn_Profile.setText(_translate("MainWindow", "Profile"))
        self.Btn_Home.setText(_translate("MainWindow", "Home"))
        item = self.tableWidgetforHome.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidgetforHome.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidgetforHome.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        __sortingEnabled = self.tableWidgetforHome.isSortingEnabled()
        self.tableWidgetforHome.setSortingEnabled(False)
        item = self.tableWidgetforHome.item(0, 0)
        item.setText(_translate("MainWindow", "House 1"))
        item = self.tableWidgetforHome.item(1, 0)
        item.setText(_translate("MainWindow", "House 2"))
        item = self.tableWidgetforHome.item(2, 0)
        item.setText(_translate("MainWindow", "Parking"))
        self.tableWidgetforHome.setSortingEnabled(__sortingEnabled)
        self.Btn_Scenes.setText(_translate("MainWindow", "Scenes"))
        self.Btn_All.setText(_translate("MainWindow", "See All"))
        item = self.tableMenu1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "NewRaw"))
        item = self.tableMenu1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "NewRaw"))
        item = self.tableMenu1.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "NewRaw"))
        item = self.tableMenu1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Floor"))
        __sortingEnabled = self.tableMenu1.isSortingEnabled()
        self.tableMenu1.setSortingEnabled(False)
        item = self.tableMenu1.item(0, 0)
        item.setText(_translate("MainWindow", "1st"))
        item = self.tableMenu1.item(1, 0)
        item.setText(_translate("MainWindow", "2st"))
        item = self.tableMenu1.item(2, 0)
        item.setText(_translate("MainWindow", "3st"))
        self.tableMenu1.setSortingEnabled(__sortingEnabled)
        item = self.tableMenu2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Rooms"))
        __sortingEnabled = self.tableMenu2.isSortingEnabled()
        self.tableMenu2.setSortingEnabled(False)
        item = self.tableMenu2.item(0, 0)
        item.setText(_translate("MainWindow", "Room 1"))
        item = self.tableMenu2.item(1, 0)
        item.setText(_translate("MainWindow", "Room 2"))
        item = self.tableMenu2.item(2, 0)
        item.setText(_translate("MainWindow", "Room 3"))
        item = self.tableMenu2.item(3, 0)
        item.setText(_translate("MainWindow", "Room 4"))
        item = self.tableMenu2.item(4, 0)
        item.setText(_translate("MainWindow", "Room 5"))
        self.tableMenu2.setSortingEnabled(__sortingEnabled)
        item = self.tableButtonsSet.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Buttons"))
        self.label_5.setText(_translate("MainWindow", "Day/Night Mode"))
        self.label_4.setText(_translate("MainWindow", "Long/Short Mode"))
        self.label_3.setText(_translate("MainWindow", "Toggle Mode"))
        self.boxButtonsChoose.setTitle(_translate("MainWindow", "Buttons"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1 - Button"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2 - Buttons"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3 - Buttons"))
        self.comboBox.setItemText(3, _translate("MainWindow", "4 - Buttons"))
        self.comboBox.setItemText(4, _translate("MainWindow", "6 - Buttons"))
        self.comboBox.setItemText(5, _translate("MainWindow", "8 - Buttons"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Comments"))
        self.textEdit.setHtml(_translate("MainWindow",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter your comments here.</p></body></html>"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Auto Find Button"))
        self.pushButton_3.setText(_translate("MainWindow", "Start"))
        self.pushButton_4.setText(_translate("MainWindow", "Cancel"))
        self.Btn_Resume_Set.setText(_translate("MainWindow", "Resume"))
        self.Btn_SaveAll_Set.setText(_translate("MainWindow", "Save All"))
        self.n1_bnt_But4.setText(_translate("MainWindow", "1"))
        self.n2_bnt_But4.setText(_translate("MainWindow", "2"))
        self.n4_bnt_But4.setText(_translate("MainWindow", "4"))
        self.n3_bnt_But4.setText(_translate("MainWindow", "3"))
        self.groupBox.setTitle(_translate("MainWindow", "Name"))
        self.Bts_Save_Name.setText(_translate("MainWindow", "Save"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Scenes"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Scenes in Button"))
        self.table_forLog.setSortingEnabled(True)
        item = self.table_forLog.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "№"))
        item = self.table_forLog.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.table_forLog.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Address"))
        item = self.table_forLog.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Data Type"))
        item = self.table_forLog.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Long/Short"))
        item = self.table_forLog.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "GateWay"))
        item = self.table_forLog.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "6"))
        item = self.table_forLog.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Comments"))
        self.Open_XML.setText(_translate("MainWindow", "Open"))
        self.Read_XML.setText(_translate("MainWindow", "Read"))
        self.Open_File_XML_ETSgroup.setText(
            _translate("MainWindow", "Folder XML file from ETS for reading information about group address"))
        self.pushButton_2.setText(_translate("MainWindow", "Reset"))
        self.pushButton.setText(_translate("MainWindow", "Save"))
        self.label.setText(_translate("MainWindow", "Oh shit something\'s wrong here!"))
        self.label_2.setText(_translate("MainWindow", "Выбери раздел тут !! Данное окно еще не реализовано. :("))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))