# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#команда для приобразования Ui файла в Py файл для работы в питоне
# >>pyuic5 -x yourfile.ui -o yourfile.py


from PyQt5 import QtCore, QtGui, QtWidgets

class Login_Dialog(object):
    def setupUi(self, interface_for_smart_house):
        interface_for_smart_house.setObjectName("interface_for_smart_house")
        interface_for_smart_house.resize(420, 630)
        interface_for_smart_house.setStyleSheet("backgroud color: rgb(45, 45, 45)")
        self.lineEdit_Login = QtWidgets.QLineEdit(interface_for_smart_house)
        self.lineEdit_Login.setGeometry(QtCore.QRect(90, 190, 240, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_Login.setFont(font)
        self.lineEdit_Login.setStyleSheet("QLineEdit {\n"
                                          "    border: 2px solid rgb(120, 120, 120);\n"
                                          "    border-radius:12px;\n"
                                          "    color: #FFF;\n"
                                          "    padding-left: 20px;\n"
                                          "    padding-right: 20px;\n"
                                          "    background-color: rgb(79, 79, 79)\n"
                                          "}\n"
                                          "QLineEdit:hover{\n"
                                          "    border: 2px solid rgb(179, 179, 179)\n"
                                          "}")
        self.lineEdit_Login.setObjectName("lineEdit_Login")
        self.frame = QtWidgets.QFrame(interface_for_smart_house)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(-1, -1, 423, 633))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: rgb(36, 36, 36);")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit_Password = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_Password.setGeometry(QtCore.QRect(90, 250, 240, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_Password.setFont(font)
        self.lineEdit_Password.setStyleSheet("QLineEdit {\n"
                                             "    border: 2px solid rgb(120, 120, 120);\n"
                                             "    border-radius:12px;\n"
                                             "    color: #FFF;\n"
                                             "    padding-left: 20px;\n"
                                             "    padding-right: 20px;\n"
                                             "    background-color: rgb(79, 79, 79)\n"
                                             "}\n"
                                             "QLineEdit:hover{\n"
                                             "    border: 2px solid rgb(179, 179, 179)\n"
                                             "}")
        self.lineEdit_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.enter_button = QtWidgets.QPushButton(self.frame)
        self.enter_button.setGeometry(QtCore.QRect(160, 320, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.enter_button.setFont(font)
        self.enter_button.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgb(70, 70, 70);\n"
                                        "    color: rgb(225, 225, 225);\n"
                                        "\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: rgb(24, 189, 249);\n"
                                        "}")
        self.enter_button.setObjectName("enter_button")
        self.forgot_button = QtWidgets.QPushButton(self.frame)
        self.forgot_button.setGeometry(QtCore.QRect(120, 560, 191, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.forgot_button.setFont(font)
        self.forgot_button.setStyleSheet("QPushButton {\n"
                                         "    font-color: rgb(255, 255, 0);\n"
                                         "    color: rgb(189, 189, 189);\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:hover {\n"
                                         "    color: rgb(255, 0, 0)\n"
                                         "}")
        self.forgot_button.setObjectName("forgot_button")
        self.dialog_window = QtWidgets.QLabel(self.frame)
        self.dialog_window.setGeometry(QtCore.QRect(100, 290, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dialog_window.setFont(font)
        self.dialog_window.setStyleSheet("color: rgb(255, 0, 0)")
        self.dialog_window.setText("")
        self.dialog_window.setObjectName("dialog_window")
        self.exitButton = QtWidgets.QPushButton(self.frame)
        self.exitButton.setGeometry(QtCore.QRect(360, 20, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.exitButton.setFont(font)
        self.exitButton.setStyleSheet("QPushButton {\n"
                                      "    color: rgb(159, 159, 159);\n"
                                      "\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover{\n"
                                      "    background-color: rgb(67, 67, 67);\n"
                                      "}")
        self.exitButton.setObjectName("exitButton")
        self.frame.raise_()
        self.lineEdit_Login.raise_()

        self.retranslateUi(interface_for_smart_house)
        QtCore.QMetaObject.connectSlotsByName(interface_for_smart_house)

    def retranslateUi(self, interface_for_smart_house):
        _translate = QtCore.QCoreApplication.translate
        interface_for_smart_house.setWindowTitle(_translate("interface_for_smart_house", "Dialog"))
        self.lineEdit_Login.setPlaceholderText(_translate("interface_for_smart_house", "Login"))
        self.lineEdit_Password.setPlaceholderText(_translate("interface_for_smart_house", "Password"))
        self.enter_button.setText(_translate("interface_for_smart_house", "Enter"))
        self.forgot_button.setText(_translate("interface_for_smart_house", "Forgotten Password?"))
        self.exitButton.setText(_translate("interface_for_smart_house", "Out"))